// -----------------------------------------------------------------------------
// csr_shadow.sv -- the double buffer between what software has written and what
// the hardware is using.
//
// THE PROBLEM
//
// A control register bank hands the design a bundle of wires that change the
// instant the processor's write lands. The processor has no idea what the design
// is doing at that instant. So a single 32-bit store from software can:
//
//   * shorten a transfer length below the count of a transfer already running,
//     so the "count reached length" test is never true again and the engine runs
//     forever -- a hang, from a legal write to a legal register;
//   * change one field for the beats at the head of a pipeline and leave the
//     beats already in flight computed with the old one, so the output is neither
//     the old configuration nor the new one;
//   * land BETWEEN the two 32-bit writes of a 64-bit parameter, so the hardware
//     sees the new high half with the old low half -- a value software never
//     asked for and cannot reproduce.
//
// None of those is a bus bug. The bus worked. The register bank worked. What is
// missing is a statement of WHEN a new configuration is allowed to take effect,
// and that statement is this module.
//
// THE SHAPE OF THE ANSWER
//
// Two copies. `staged` is what software has written and may change at any time.
// `active` is what the hardware uses and changes only at a commit. A commit
// copies ALL of `staged` in one cycle, and only when the consumer says it is
// safe. That gives three properties for the price of one register bank:
//
//   ATOMICITY   every field changes in the same cycle, so a multi-word update is
//               never torn no matter how software spreads it over the bus.
//   ISOLATION   `active` is stable across whatever the consumer defines as its
//               critical region, so an FSM's terminal condition cannot move
//               under it.
//   VISIBILITY  `pending` tells software the write has not taken effect yet, and
//               `applied` is a one-cycle event it can turn into an interrupt.
//
// MODE -- the commit policy, which is the only real decision here:
//
//   0 TRANSPARENT  active = staged. No protection at all. This is not a
//                  degenerate configuration for completeness; it is the negative
//                  control. docs/39 section 11 runs the same proofs against it,
//                  and they fail, which is how the other modes are known to be
//                  testing anything.
//   1 SAFE_POINT   commit whenever the consumer is safe and something differs.
//                  Software writes and forgets; the update lands at the next
//                  boundary. Costs a comparator as wide as the bundle.
//   2 ARM_COMMIT   commit when software has armed it AND the consumer is safe.
//                  Software controls the grouping, which is what you want when
//                  "the new configuration" is six registers that are only
//                  meaningful together.
//
// ARM IS A WRITE STROBE, NOT A BIT
//
// `arm` is expected to be a decoded write pulse -- one cycle, generated by the
// address decode, never stored. The alternative is a real flop software sets and
// hardware clears, and that races: software reads it back as still set and
// cannot tell "not started" from "started, nearly done". A command register is
// an event. See csr_ctrl_top.sv for the decode.
//
// THE HAZARD THIS MODULE DOES NOT REMOVE
//
// Software must write every register and THEN arm. If it arms and keeps writing,
// a commit can land mid-sequence and publish half the new configuration
// atomically -- atomically wrong. `lock` is asserted while a commit is pending so
// the integrator can turn a write in that window into a bus error rather than
// into a field failure; csr_ctrl_top.sv does exactly that. It detects a driver
// bug, it does not prevent one.
//
// See docs/39-control-registers-and-safe-reconfiguration.md.
// -----------------------------------------------------------------------------
`default_nettype none

module csr_shadow #(
  parameter int unsigned NREG = 4,
  parameter int unsigned DW   = 32,
  parameter int unsigned MODE = 2
) (
  input  var logic               clk,
  input  var logic               rst_n,

  // Software side.
  input  var logic [NREG*DW-1:0] staged,   // straight off the register bank
  input  var logic               arm,      // decoded write strobe, one cycle
  output var logic               pending,  // armed, waiting for `safe`
  output var logic               applied,  // one cycle: `active` just changed
  output var logic               lock,     // reject writes while this is high

  // Hardware side.
  input  var logic               safe,     // the consumer's critical region is closed
  output var logic [NREG*DW-1:0] active    // what the design must actually use
);

  localparam int unsigned M_TRANSPARENT = 0;
  localparam int unsigned M_SAFE_POINT  = 1;
  localparam int unsigned M_ARM_COMMIT  = 2;

  logic commit;

  if (MODE == M_TRANSPARENT) begin : g_transparent
    // No storage, no commit point, no protection. Kept so that every proof and
    // every testbench pass in docs/39 can be pointed at the unprotected design
    // without writing a second one.
    assign active  = staged;
    assign commit  = 1'b0;
    assign pending = 1'b0;
    assign applied = 1'b0;
    assign lock    = 1'b0;

  end else begin : g_buffered
    logic [NREG*DW-1:0] active_q;
    logic               applied_q;

    assign active  = active_q;
    assign applied = applied_q;

    if (MODE == M_SAFE_POINT) begin : g_auto
      // One comparator as wide as the whole bundle. It is the price of "software
      // writes and forgets": without it this mode cannot tell a pending update
      // from a quiet one, so `pending` and `applied` would be noise. It is the
      // dominant cost of MODE 1 -- 251 of its 385 cells, measured in docs/39
      // section 6 -- and the reason MODE 2 does not compute it at all.
      logic dirty;
      assign dirty = (staged != active_q);

      assign commit  = safe && dirty;
      assign pending = dirty;      // software's write has not landed yet
      assign lock    = 1'b0;       // nothing to lock: there is no arm to race

    end else begin : g_armed
      logic pend_q;

      // An arm while an arm is already PENDING is absorbed, not queued: there is
      // nothing to queue, because a commit publishes whatever is staged at that
      // moment, so two arms and one commit is the same outcome as two arms and two
      // commits with no writes in between.
      //
      // An arm coinciding with a COMMIT is a different case, and the priority
      // below is deliberate rather than incidental. `arm` beats `commit`, so
      // pend_q stays set and a second commit follows -- which is right, because
      // that arm refers to whatever software staged after the first one was
      // already decided. Ordering these the other way round would drop it.
      always_ff @(posedge clk or negedge rst_n) begin
        if      (!rst_n) pend_q <= 1'b0;
        else if (arm)    pend_q <= 1'b1;
        else if (commit) pend_q <= 1'b0;
      end

      assign commit  = pend_q && safe;
      assign pending = pend_q;
      assign lock    = pend_q;
    end

    always_ff @(posedge clk or negedge rst_n) begin
      if (!rst_n) begin
        active_q  <= '0;
        applied_q <= 1'b0;
      end else begin
        // The whole bundle, one enable. That single line is the atomicity
        // guarantee: there is no ordering for software to get wrong because
        // there is no ordering.
        if (commit) active_q <= staged;
        applied_q <= commit;
      end
    end
  end

`ifdef FORMAL
  // Shadow copies rather than $past of a 128-bit vector: the assertions below
  // are the specification of this module and they should not depend on how well
  // any particular tool handles $past of a wide expression (docs/37 section 13
  // records the simulator that gets it wrong).
  logic                f_rst_q  = 1'b0;
  logic                f_com_q  = 1'b0;
  logic                f_arm_q  = 1'b0;
  logic                f_pend_q = 1'b0;
  logic [NREG*DW-1:0]  f_act_q;
  logic [NREG*DW-1:0]  f_stg_q;

  always_ff @(posedge clk) begin
    f_rst_q  <= rst_n;
    f_com_q  <= commit;
    f_arm_q  <= arm;
    f_pend_q <= pending;
    f_act_q  <= active;
    f_stg_q  <= staged;
  end

  if (MODE != M_TRANSPARENT) begin : g_fv
    always @(posedge clk) begin
      if (rst_n && f_rst_q) begin
        // (1) `active` moves only at a commit. This is ISOLATION: everything the
        // consumer relies on being stable is stable, by construction, for as
        // long as it keeps `safe` low.
        if (!f_com_q) assert (active == f_act_q);

        // (2) and when it moves it takes the WHOLE of `staged`. This is
        // ATOMICITY, and stating it over the full vector rather than per field
        // is what makes a torn multi-word update unrepresentable.
        if (f_com_q) assert (active == f_stg_q);

        // (3) a commit never happens outside the consumer's permission.
        if (commit) assert (safe);

        // (4) the software-visible pulse is exactly the commit, delayed one
        // cycle. An `applied` that can fire without a commit would have software
        // believing a configuration is live when it is not.
        assert (applied == f_com_q);
      end

      if (rst_n && f_rst_q && (MODE == M_ARM_COMMIT)) begin
        // (5) an arm is never dropped -- however long `safe` stays low, and also
        // when it lands on the very cycle a commit is being taken. Stated
        // unconditionally rather than as `f_arm_q && !f_com_q`, which is how it
        // was written first and which left the coincident case vacuous: exactly
        // the case where getting the register's priority backwards would lose a
        // configuration update.
        if (f_arm_q) assert (pending);
        // (6) and `pending` clears only by being honoured.
        if (f_pend_q && !f_com_q) assert (pending);
      end

      if (rst_n && (MODE == M_SAFE_POINT)) begin
        // (7) in the automatic mode `pending` means exactly "not yet equal".
        assert (pending == (staged != active));
      end
    end
  end
`endif

`ifndef SYNTHESIS
  a_atomic: assert property (@(posedge clk) disable iff (!rst_n)
    (MODE != M_TRANSPARENT) && !commit |=> $stable(active))
    else $error("csr_shadow: active configuration changed without a commit");

  a_commit_safe: assert property (@(posedge clk) disable iff (!rst_n)
    (MODE != M_TRANSPARENT) && commit |-> safe)
    else $error("csr_shadow: committed while the consumer was not safe");
`endif

endmodule

`default_nettype wire
